import math
import os
import random
import re
import sys

#
# Complete the 'alternatingCharacters' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def alternatingCharacters(s):
    # Write your code here
    deletionCount = 0
    for i in range(len(s)-1):
        if s[i]==s[i+1]:
            s.replace(s[i],'')
            deletionCount +=1
    print(deletionCount)
    return deletionCount


s= 'BAAAAAABBBABABBBAABABABBBBAAABABBABBABBBABBAAAAABBAABABABBAAAABBABBBAAABBBBBABBBABBBBBBBABBBBAAABBBABBBABABBAAAAABABABABBBAAAAABABBBBAAABBBBABBAABBBBAAABAABABBAAAABBABABABBBABAABBBBBBABBABABABBAAAAAABABBAAAAABBBAAABBBBAAAABBABAABAAAABAABAABBBBBBAAABAABBBBBBBAABAABBABAABBBABABBAABBAAAABBBABBABABAABBBAAABBBABBAAABAABAAAABBABBABABABBBBAAABBABBAAABBABBAABBBABBAABBBABABBBABAAABABAAAAAABBABABAAABABAAAABABBABAAABAABBBAABBBABBABBBBBBBAABAAAABBBBBAAAABBAABBBAABBAABBBBABBBBAABABBAAABBABBBBBAAAAABBBAAAABAABBAAABAAAAAABABAABAABABBABBAABBBABABAABBAABBAABABAAAABBABBBBAABBBBAABBBABABBABBBBBBBBBBAAABAAABABBABBBBABAABBBAABBBAABAABBBAAAABAAABBBBAABBBBBAAABABAABABAABBABBABABBBBBBAAABAABAAAAAAABAABBAAAABABAAABBAABBABBABBBBBBAAABBABABBAABABBBBBABBBAAABBBBAABABABBAAABABBBABBBBABBABBBABAABBBAAABAABBABBABABBBBAABBAABBBBAAAAAAABABABABBABABBBBBAABABABAAABBABBBAAABBBABBAAABBBBBBBABBAABBBBBABBABABAAABAABBBBAAABABABBBAABBAAABBAABABBABABBBBBBBABBBABBBABBABABABAAABBBAAABAABBAAABABABBBBBBBABABBAAAAABAABABAABABBAABBBABABBBAABABBABABBBBABA{-truncated-}'
alternatingCharacters(s)